// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRuleRequest struct {
	Rule                 *Rule    `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleRequest) Reset()         { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()    {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(dst, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type CreateRuleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleResponse) Reset()         { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()    {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (dst *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(dst, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

type RemoveRuleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Program              string   `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRuleRequest) Reset()         { *m = RemoveRuleRequest{} }
func (m *RemoveRuleRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRuleRequest) ProtoMessage()    {}
func (*RemoveRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *RemoveRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRuleRequest.Unmarshal(m, b)
}
func (m *RemoveRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRuleRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRuleRequest.Merge(dst, src)
}
func (m *RemoveRuleRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRuleRequest.Size(m)
}
func (m *RemoveRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRuleRequest proto.InternalMessageInfo

func (m *RemoveRuleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveRuleRequest) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

type RemoveRuleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRuleResponse) Reset()         { *m = RemoveRuleResponse{} }
func (m *RemoveRuleResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRuleResponse) ProtoMessage()    {}
func (*RemoveRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *RemoveRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRuleResponse.Unmarshal(m, b)
}
func (m *RemoveRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRuleResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRuleResponse.Merge(dst, src)
}
func (m *RemoveRuleResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRuleResponse.Size(m)
}
func (m *RemoveRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRuleResponse proto.InternalMessageInfo

type ListRulesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRulesRequest) Reset()         { *m = ListRulesRequest{} }
func (m *ListRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRulesRequest) ProtoMessage()    {}
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *ListRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesRequest.Unmarshal(m, b)
}
func (m *ListRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesRequest.Marshal(b, m, deterministic)
}
func (dst *ListRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesRequest.Merge(dst, src)
}
func (m *ListRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRulesRequest.Size(m)
}
func (m *ListRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesRequest proto.InternalMessageInfo

type Rule struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Program              string             `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	FilterEvents         map[string]*Filter `protobuf:"bytes,3,rep,name=filterEvents,proto3" json:"filterEvents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContainerRuntimes    []string           `protobuf:"bytes,4,rep,name=containerRuntimes,proto3" json:"containerRuntimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *Rule) GetFilterEvents() map[string]*Filter {
	if m != nil {
		return m.FilterEvents
	}
	return nil
}

func (m *Rule) GetContainerRuntimes() []string {
	if m != nil {
		return m.ContainerRuntimes
	}
	return nil
}

type Filter struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ListRulesResponse struct {
	Rules                []*Rule  `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRulesResponse) Reset()         { *m = ListRulesResponse{} }
func (m *ListRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRulesResponse) ProtoMessage()    {}
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}
func (m *ListRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesResponse.Unmarshal(m, b)
}
func (m *ListRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesResponse.Merge(dst, src)
}
func (m *ListRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRulesResponse.Size(m)
}
func (m *ListRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesResponse proto.InternalMessageInfo

func (m *ListRulesResponse) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRuleRequest)(nil), "types.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "types.CreateRuleResponse")
	proto.RegisterType((*RemoveRuleRequest)(nil), "types.RemoveRuleRequest")
	proto.RegisterType((*RemoveRuleResponse)(nil), "types.RemoveRuleResponse")
	proto.RegisterType((*ListRulesRequest)(nil), "types.ListRulesRequest")
	proto.RegisterType((*Rule)(nil), "types.Rule")
	proto.RegisterMapType((map[string]*Filter)(nil), "types.Rule.FilterEventsEntry")
	proto.RegisterType((*Filter)(nil), "types.Filter")
	proto.RegisterType((*ListRulesResponse)(nil), "types.ListRulesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error)
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/types.API/CreateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error) {
	out := new(RemoveRuleResponse)
	err := c.cc.Invoke(ctx, "/types.API/RemoveRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, "/types.API/ListRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	CreateRule(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	RemoveRule(context.Context, *RemoveRuleRequest) (*RemoveRuleResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/CreateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/RemoveRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).RemoveRule(ctx, req.(*RemoveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/ListRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRule",
			Handler:    _API_CreateRule_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _API_RemoveRule_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _API_ListRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0x26, 0xcd, 0x4b, 0xa6, 0xaf, 0xd0, 0x0c, 0xa2, 0x6b, 0x41, 0x8c, 0xf1, 0x92,
	0x83, 0xe4, 0x50, 0x45, 0xc4, 0x93, 0xb5, 0x54, 0x10, 0x44, 0x64, 0x8f, 0xde, 0x62, 0x59, 0x4b,
	0x30, 0xff, 0xdc, 0xdd, 0x14, 0xfa, 0x31, 0xfd, 0x30, 0xde, 0x25, 0x9b, 0x6d, 0x9b, 0x36, 0xbd,
	0x78, 0xdb, 0x9d, 0x67, 0xe6, 0x37, 0xbb, 0xf3, 0x0c, 0x38, 0x51, 0x11, 0x87, 0x05, 0xcf, 0x65,
	0x8e, 0x3d, 0xb9, 0x2c, 0x98, 0xf0, 0xaf, 0xc1, 0x9d, 0x70, 0x16, 0x49, 0x46, 0xcb, 0x84, 0x51,
	0xf6, 0x55, 0x32, 0x21, 0xf1, 0x0c, 0x2c, 0x5e, 0x26, 0x8c, 0x74, 0x3d, 0x23, 0xe8, 0x8f, 0xfa,
	0xa1, 0x4a, 0x0d, 0x55, 0x86, 0x12, 0xfc, 0x43, 0xc0, 0x66, 0x95, 0x28, 0xf2, 0x4c, 0x30, 0x7f,
	0x0c, 0x2e, 0x65, 0x69, 0xbe, 0xd8, 0x62, 0x21, 0x58, 0x59, 0x94, 0x32, 0x62, 0x78, 0x46, 0xe0,
	0x50, 0x75, 0x46, 0x02, 0xff, 0x0a, 0x9e, 0xcf, 0x79, 0x94, 0xaa, 0x16, 0x0e, 0x5d, 0x5d, 0x2b,
	0x70, 0x13, 0xa1, 0xc1, 0x08, 0x83, 0xe7, 0x58, 0xc8, 0x2a, 0x26, 0x34, 0xd7, 0xff, 0x31, 0xc0,
	0xaa, 0x02, 0x7f, 0x6b, 0x80, 0x63, 0xf8, 0xff, 0x11, 0x27, 0x92, 0xf1, 0xe9, 0x82, 0x65, 0x52,
	0x10, 0xd3, 0x33, 0x83, 0xfe, 0xe8, 0xb4, 0xf1, 0xc5, 0xf0, 0xb1, 0xa1, 0x4f, 0x33, 0xc9, 0x97,
	0x74, 0xab, 0x04, 0x2f, 0xc1, 0x9d, 0xe5, 0x99, 0x8c, 0xe2, 0x8c, 0x71, 0x5a, 0x66, 0x32, 0x4e,
	0x99, 0x20, 0x96, 0x67, 0x06, 0x0e, 0x6d, 0x0b, 0xc3, 0x17, 0x70, 0x5b, 0x40, 0x1c, 0x80, 0xf9,
	0xc9, 0x96, 0xfa, 0xc9, 0xd5, 0x11, 0x2f, 0xa0, 0xb7, 0x88, 0x92, 0x72, 0x35, 0xf3, 0x03, 0xfd,
	0xa0, 0xba, 0x94, 0xd6, 0xda, 0x5d, 0xf7, 0xd6, 0xf0, 0x3d, 0xb0, 0xeb, 0x20, 0x1e, 0x81, 0xad,
	0xc2, 0x82, 0x18, 0xaa, 0xb9, 0xbe, 0xf9, 0x37, 0xe0, 0x36, 0xa6, 0x55, 0x8f, 0x10, 0xcf, 0xa1,
	0x57, 0x39, 0x57, 0xe7, 0xee, 0x78, 0x5a, 0x2b, 0xa3, 0x6f, 0x03, 0xcc, 0xf1, 0xeb, 0x13, 0x4e,
	0x00, 0x36, 0xe6, 0x22, 0xd1, 0x99, 0xad, 0x2d, 0x19, 0x9e, 0xec, 0x51, 0xb4, 0x61, 0x9d, 0x0a,
	0xb2, 0x31, 0x72, 0x0d, 0x69, 0xad, 0xc7, 0x1a, 0xb2, 0xc7, 0xf5, 0x0e, 0xde, 0x83, 0xb3, 0xfe,
	0x09, 0x1e, 0xeb, 0xcc, 0xdd, 0x4d, 0x18, 0x92, 0xb6, 0xb0, 0x22, 0x3c, 0xd8, 0x6f, 0xd6, 0x9c,
	0x17, 0xb3, 0x77, 0x5b, 0x2d, 0xfd, 0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x6b, 0x6b,
	0xb3, 0x01, 0x03, 0x00, 0x00,
}
